apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: deployments/argocd/argocd-image-updater/
    repoURL: https://github.com/spoukke/kubernetes-cluster-state.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
