apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: deployments/argocd/argo/
    repoURL: https://github.com/spoukke/kuberntes-cluster-state.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
